### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by madeinyashiro** [armateam/extension#2]
Hello !

Merci pour cette chouette extension !

Tu penses qu'serait possible d'ajouter le planning des streams de la team directement à l'addon ? Comme ça pas besoin de charger Twitch pour le voir :)

Merci d'avance et bonne continuation.
Yashiro

**Comment by tusbar** [comment]
Hello @madeinyashiro,

Merci. :)

Il faudrait que le planning soit accessible quelque part, pour ne pas avoir à le modifier à chaque fois qu’il change ici, je vais voir ce qui est possible.

**Comment by madeinyashiro** [comment]
Peut-être demander à la team de fournir le planning avec la même URL à chaque fois et archiver les anciens planning dans un dossier avec un nom plus parleur. Bref, c'était juste une idée comme ça :+1:

**Comment by tusbar** [comment]
@madeinyashiro peut être que ça va venir : https://twitter.com/tusbar/status/923129945949376512 :)
